Update containerdeployment.yml

diff --git a/.github/workflows/containerdeployment.yml b/.github/workflows/containerdeployment.yml
--- a/.github/workflows/containerdeployment.yml
+++ b/.github/workflows/containerdeployment.yml
@@ -16,10 +16,10 @@ jobs:
     steps:
       - name: Check out the repo
         uses: actions/checkout@v3
-        
-      - name: Looking for files
-        run: ls -a
-        
+      
+      - name: Verify Dockerfile existence
+        run: test -f path/to/Dockerfile || echo "Dockerfile not found"
+
       - name: Build Docker NET image
-        run: | 
-          docker build --platform linux -t $IMAGE_BASE_NAME .
+        run: |
+          docker build --platform linux -t $IMAGE_BASE_NAME -f path/to/Dockerfile .
